version: "3.9"
services:
  web:
    image: rv3392/uq-bus-web
    build: 
      context: ./web/
      args:
        REACT_APP_API_URL: "http://${EXTERNAL_SWARM_IP}:5000"
    ports:
      - 80:80
  seq-transport-api:
    image: rv3392/uq-bus-api
    build: ./api/
    ports:
      - 5000:5000
    environment:
      DB_HOST: uq-bus_seq-gtfs-database
      DB_USER: seq-gtfs
      DB_PASSWORD: password
      DB_PORT: 5432
      DB_NAME: seq-gtfs
    entrypoint: ["./wait-for-it.sh", "uq-bus_seq-gtfs-database:5432", "-t", "0", "--", "python", "app.py"]
